### ISSUE TITLE
Doesn't seem to work on Ubuntu

### ISSUE THREAD

**Issue by Bastes** [oh-my-fish/plugin-jump#2]
Hi,

I've just tried to install this plugin ; installing from its name just doesn't work (neither "omf install jump" nor "omf install plugin-jump" did the trick), I resorted to install from the URL and did:
```
omf uninstall https://github.com/oh-my-fish/plugin-jump.git
```

That seemed to do the trick, although when I try to mark a directory, it always answers with:
```
test: Missing argument at index 1
/whatever-mark-name already exists.
```

Of course, when I try to jump at the mark, it doesn't work either:
```
test: Missing argument at index 1
No such mark: whatever-mark-name
```

Using "marks" gives an even more puzzling result:
```
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
test: Missing argument at index 1
No marks currently defined.
```

I'm using Ubuntu 15.04 with a brand new fish and oh-my-fish install.

**Comment by bpinto** [comment]
This plugin has not been converted to the new architecture yet. Perhaps @scorphus could assist you?

**Comment by Bastes** [comment]
That explains it ^^° sorry for the noise, I'll be sure to come back and try when it's good and ready.

**Comment by bpinto** [comment]
Its okay, we broke backwards compatibility :(

**Comment by bpinto** [comment]
Check out #3. We are going to merge the fix soon.

**Comment by Bastes** [comment]
Cool ^^ I'll be sure to try it then. Thanks for your awesome work ^^

**Comment by bpinto** [comment]
:+1: You too for your recent contributions :)

**Comment by Bastes** [comment]
Always happy to help, however little ^^

**Comment by portenez** [comment]
I just gave this a try, and it is still not working on ubuntu. :disappointed: . Am I doing something wrong? I'm installing this using:

```
omf install https://github.com/oh-my-fish/plugin-jump.git
```

**Comment by portenez** [comment]
I figured that if I call 

```
omf install https://github.com/oh-my-fish/plugin-jump.git
```

it creates a dir:
$OMF_PATH/pkg/jump.git, if I rename this to jump, then things work.

**Comment by derekstavis** [comment]
Yes. Fix for this is coming in https://github.com/oh-my-fish/oh-my-fish/commit/d376e086b40c2b00e4925d855da39628f5362d8c

**Comment by portenez** [comment]
Awesome, thanks!

**Comment by Bastes** [comment]
Go OMF ^^d
